### ISSUE TITLE
Missing git info icons in nerd-tree

### ISSUE THREAD

**Issue by dazorni** [sharpner/dotfiles-ng#7]
Currently the git info icons in nerd tree are missing in **alacritty** see screenshots. The filetypes are okay. (Tested for js and php)

### Terminal:
<img width="220" alt="bildschirmfoto 2017-09-14 um 17 06 37" src="https://user-images.githubusercontent.com/1658380/30437548-2ba08f26-996f-11e7-8d4f-c2bf5233acf2.png">

### Alacritty
<img width="213" alt="bildschirmfoto 2017-09-14 um 17 07 26" src="https://user-images.githubusercontent.com/1658380/30437563-352bd316-996f-11e7-8fec-213a101ddd19.png">

**Comment by sharpner** [comment]
fixed
